import{a as w,S,i as a}from"./assets/vendor-Z6SuAarM.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&c(l)}).observe(document,{childList:!0,subtree:!0});function r(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function c(e){if(e.ep)return;e.ep=!0;const s=r(e);fetch(e.href,s)}})();const v="54334206-17d8f163cff9d1cc5aaf27ec6",q="https://pixabay.com/api/";async function u(o,t=1){const r={key:v,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15};return(await w.get(q,{params:r})).data}const f=document.querySelector(".gallery"),h=document.querySelector(".loader"),p=document.querySelector(".load-more"),R=new S(".gallery a",{captionsData:"alt",captionDelay:250});function m(o){const t=o.map(r=>`
      <li class="gallery-item">
        <a href="${r.largeImageURL}">
          <img src="${r.webformatURL}" alt="${r.tags}" />
        </a>
        <div class="info">
          <p><b>Likes</b> ${r.likes}</p>
          <p><b>Views</b> ${r.views}</p>
          <p><b>Comments</b> ${r.comments}</p>
          <p><b>Downloads</b> ${r.downloads}</p>
        </div>
      </li>
    `).join("");f.insertAdjacentHTML("beforeend",t),R.refresh()}function B(){f.innerHTML=""}function y(){h.classList.remove("is-hidden")}function g(){h.classList.add("is-hidden")}function L(){p.classList.remove("is-hidden")}function b(){p.classList.add("is-hidden")}const M=document.querySelector(".form"),P=document.querySelector(".load-more");let i="",n=1,d=0;M.addEventListener("submit",$);P.addEventListener("click",E);async function $(o){if(o.preventDefault(),i=o.target.elements["search-text"].value.trim(),n=1,!!i){B(),b(),y();try{const t=await u(i,n);if(d=t.totalHits,t.hits.length===0){a.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}m(t.hits),n*15<d?L():a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}catch{a.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{g()}}}async function E(){n+=1,b(),y();try{const o=await u(i,n);m(o.hits),O(),n*15<d?L():a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}catch{a.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{g()}}function O(){const o=document.querySelector(".gallery-item");if(!o)return;const{height:t}=o.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
