import{a as b,S as w,i as l}from"./assets/vendor-Z6SuAarM.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const n of e)if(n.type==="childList")for(const c of n.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function r(e){const n={};return e.integrity&&(n.integrity=e.integrity),e.referrerPolicy&&(n.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?n.credentials="include":e.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function i(e){if(e.ep)return;e.ep=!0;const n=r(e);fetch(e.href,n)}})();const S="54334206-17d8f163cff9d1cc5aaf27ec6",v="https://pixabay.com/api/";async function u(o,t=1){const r={key:S,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15};return(await b.get(v,{params:r})).data}const f=document.querySelector(".gallery"),p=document.querySelector(".loader"),m=document.querySelector(".load-more"),q=new w(".gallery a",{captionsData:"alt",captionDelay:250});function h(o){const t=o.map(r=>`
      <li class="gallery-item">
        <a href="${r.largeImageURL}">
          <img src="${r.webformatURL}" alt="${r.tags}" />
        </a>
        <div class="info">
          <p><b>Likes</b> ${r.likes}</p>
          <p><b>Views</b> ${r.views}</p>
          <p><b>Comments</b> ${r.comments}</p>
          <p><b>Downloads</b> ${r.downloads}</p>
        </div>
      </li>
    `).join("");f.insertAdjacentHTML("beforeend",t),q.refresh()}function B(){f.innerHTML=""}function y(){p.classList.remove("is-hidden")}function g(){p.classList.add("is-hidden")}function M(){m.classList.remove("is-hidden")}function L(){m.classList.add("is-hidden")}const $=document.querySelector(".form"),E=document.querySelector(".load-more");let a="",s=1,d=0;$.addEventListener("submit",P);E.addEventListener("click",R);async function P(o){if(o.preventDefault(),a=o.target.elements["search-text"].value.trim(),s=1,!!a){B(),L(),y();try{const t=await u(a,s);if(d=t.totalHits,t.hits.length===0){l.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}h(t.hits),s*15<d&&M()}catch{l.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{g()}}}async function R(){s+=1,y();try{const o=await u(a,s);h(o.hits),O(),s*15>=d&&(L(),l.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}finally{g()}}function O(){const o=document.querySelector(".gallery-item");if(!o)return;const{height:t}=o.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
